services:
  mysql.integration:
    volumes:
      - .docker/mysql:/etc/mysql/tmp
      - ./mysqldata-integration:/var/lib/mysql
      - .docker/mysql/repository:/docker-entrypoint-initdb.d
      - .docker/mysql/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./logs-integration:/var/log/mysql

