networks:
  cms-net:
    driver: bridge

services:
  console.poliziadistato.localhost:
    platform: linux/amd64
    image: httpd:2.4.55
    ports:
      - "80:80"
      - "8181:80"
    environment:
      - CI_ENV=development
    networks:
      cms-net:
        aliases:
          - console.poliziadistato.local
          - console.poliziadistato.localhost
          - www.poliziadistato.localhost
          - poliziadistato.localhost
          - questure.poliziadistato.localhost
          - doppiavela.poliziadistato.localhost
          - dv.poliziadistato.localhost
          - poliziamoderna.poliziadistato.localhost
    volumes:
      - .docker/httpd/conf:/usr/local/apache2/conf
      - ./statics:/var/www/statics
      - ./WWW:/var/www/html/WWW
      - ./WWW_DOPPIAVELA:/var/www/html/WWW_DOPPIAVELA
      - ./WWW_DOPPIAVELA_INTERNET:/var/www/html/WWW_DOPPIAVELA_INTERNET
      - ./WWW_POLIZIADISTATO:/var/www/html/WWW_POLIZIADISTATO
      - ./WWW_POLIZIAMODERNA:/var/www/html/WWW_POLIZIAMODERNA
      - ./WWW_QUESTURE:/var/www/html/WWW_QUESTURE
      - ./mod_cache-lock:/usr/local/apache2/mod_cache-lock
      - ./mod_cache_disk:/usr/local/apache2/mod_cache_disk

  php:
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    network_mode: "service:console.poliziadistato.localhost"
    volumes:
      - .:/var/www/html
      - ./statics:/var/www/statics
      - ./WWW:/var/www/html/WWW
      - ./WWW_DOPPIAVELA:/var/www/html/WWW_DOPPIAVELA
      - ./WWW_DOPPIAVELA_INTERNET:/var/www/html/WWW_DOPPIAVELA_INTERNET
      - ./WWW_POLIZIADISTATO:/var/www/html/WWW_POLIZIADISTATO
      - ./WWW_POLIZIAMODERNA:/var/www/html/WWW_POLIZIAMODERNA
      - ./WWW_QUESTURE:/var/www/html/WWW_QUESTURE
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - console.poliziadistato.localhost
      - redis

  mysql:
    platform: linux/amd64
    image: mysql:8.0.34
    ports:
      - "13306:3306"
    networks:
      - cms-net
    volumes:
      - ./logs:/var/log/mysql
      - ./mysqldata:/var/lib/mysql
      - .docker/mysql:/etc/mysql/tmp
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Rome
    command: >
      bash -c "

      cd /var/lib/mysql
      && find . -type f -name '._*' -delete
      && cp /etc/mysql/tmp/*.cnf /etc/mysql/conf.d/
      && chmod 644 /etc/mysql/conf.d/*.cnf
      && ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime
      && /entrypoint.sh mysqld
      "

  redis:
    platform: linux/amd64
    image: redis:7
    ports:
      - "6379:7379"
    volumes:
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - cms-net
    command:
      bash -c "
      chmod 644 /usr/local/etc/redis/redis.conf;
      redis-server /usr/local/etc/redis/redis.conf
      "

  mysql.integration:
    platform: linux/amd64
    image: mysql:8.0.34
    ports:
      - "13307:3306"
    networks:
      - cms-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Rome
    command: >
      bash -c "

      cd /var/lib/mysql
      && rm -rf /var/lib/mysql/*
      && cp /etc/mysql/tmp/*.cnf /etc/mysql/conf.d/
      && chmod 644 /etc/mysql/conf.d/*.cnf
      && cp -f /usr/local/bin/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
      && chmod 555 /usr/local/bin/docker-entrypoint.sh
      && ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime
      && /entrypoint.sh mysqld
      "

  console.poliziadistato.integration:
    platform: linux/amd64
    image: httpd:2.4.55
    ports:
      - "81:80"
    environment:
      - CI_ENV=integration
    networks:
      - cms-net
    volumes:
      - .docker/httpd-integration/conf:/usr/local/apache2/conf
      - ./laravel-pds:/var/www/html/laravel-pds
      - ./laravel-qst:/var/www/html/laravel-qst
      - ./laravel-pzm:/var/www/html/laravel-pzm
      - ./mod_cache-lock:/usr/local/apache2/mod_cache-lock
      - ./mod_cache_disk:/usr/local/apache2/mod_cache_disk

  php8.3.integration:
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/php8.3/Dockerfile
    network_mode: "service:console.poliziadistato.integration"
    volumes:
      - ./laravel-pds:/var/www/html/laravel-pds
      - ./laravel-qst:/var/www/html/laravel-qst
      - ./laravel-pzm:/var/www/html/laravel-pzm
      - ./statics:/var/www/statics
      - .docker/php8.3/php.ini:/usr/local/etc/php/php.ini
      - .docker/php8.3/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - .docker/php8.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/php8.3/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - console.poliziadistato.integration
