#docker compose up -d
networks:
  cms-net:
    driver: bridge

services:
  laravel.localhost:
    build:
      context: .
      dockerfile: .docker/laravel/Dockerfile
    ports:
      - "9000:80"
    volumes:
#      - .docker/laravel/php/php.ini-development:/usr/local/etc/php/
      - ./laravel-pds:/var/www/html
#      - /var/www/html/storage # Storage for Laravel's storage folder
#      - /var/www/html/bootstrap/cache # Storage for Laravel's cache
    environment:
      - CI_ENV=development
      - API_URL=http://console.poliziadistato.localhost:8181
    networks:
      - cms-net
    mem_limit: "2G"
    cpus: "1"

  console.poliziadistato.localhost:
    platform: linux/amd64
    image: httpd:2.4.55
    ports:
      - "80:80"
      - "8181:80"
#      - "9000:9000"
    environment:
      - CI_ENV=development
    networks:
      - cms-net
    volumes:
      - .docker/httpd/conf:/usr/local/apache2/conf
      - .:/var/www/html
      - ./mod_cache-lock:/usr/local/apache2/mod_cache-lock
      - ./mod_cache_disk:/usr/local/apache2/mod_cache_disk

  php:
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    network_mode: "service:console.poliziadistato.localhost"
    volumes:
      - .:/var/www/html
      - ./statics:/var/www/statics
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - redis

  mysql:
    platform: linux/amd64
    image: mysql:8.0.34
    ports:
      - "13306:3306"
    networks:
      - cms-net
    volumes:
      - ./logs:/var/log/mysql
      - ./mysqldata:/var/lib/mysql
      - .docker/mysql:/etc/mysql/tmp
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Rome
    command: >
      bash -c "
      
      cd /var/lib/mysql
      && find . -type f -name '._*' -delete
      && cp /etc/mysql/tmp/*.cnf /etc/mysql/conf.d/
      && chmod 644 /etc/mysql/conf.d/*.cnf
      && ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime
      && /entrypoint.sh mysqld
      "

  redis:
    platform: linux/amd64
    image: redis:7
    ports:
      - "6379:7379"
    volumes:
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - cms-net
    command:
      bash -c "
      chmod 644 /usr/local/etc/redis/redis.conf;
      redis-server /usr/local/etc/redis/redis.conf
      "

  console.poliziadistato.integration:
    platform: linux/amd64
    image: httpd:2.4.55
    ports:
      - "81:80"
    environment:
      - CI_ENV=integration
    networks:
      cms-net:
        #servono per accedere agli host dai container di test (jest, cypress) durante la CI
        aliases:
          - www.poliziadistato.localhost
          - poliziadistato.localhost
          - questure.poliziadistato.localhost
          - doppiavela.poliziadistato.localhost
          - dv.poliziadistato.localhost
          - poliziamoderna.poliziadistato.localhost
          - console.poliziadistato.localhost
    volumes:
      - .docker/httpd/conf:/usr/local/apache2/conf
      - .:/var/www/html
      - ./mod_cache-lock:/usr/local/apache2/mod_cache-lock
      - ./mod_cache_disk:/usr/local/apache2/mod_cache_disk

  php.integration:
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    network_mode: "service:console.poliziadistato.integration"
    volumes:
      - .:/var/www/html
      - ./statics:/var/www/statics
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - console.poliziadistato.integration
    command: >
      bash -c "
      chmod -R o+rw /var/www/html/statics;
      chmod -R o+rw /var/www/statics;
      chmod -R o+rw /tmp;
      php-fpm
      "

  mysql.integration:
    platform: linux/amd64
    image: mysql:8.0.34
    ports:
      - "13307:3306"
    networks:
      - cms-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Rome
    command: >
      bash -c "
      
      cd /var/lib/mysql
      && rm -rf /var/lib/mysql/*
      && cp /etc/mysql/tmp/*.cnf /etc/mysql/conf.d/
      && chmod 644 /etc/mysql/conf.d/*.cnf
      && cp -f /usr/local/bin/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
      && chmod 555 /usr/local/bin/docker-entrypoint.sh
      && ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime
      && /entrypoint.sh mysqld
      "