INSERT INTO cms2015.fsm (id, code, description, items_table_name, items_table_key_field) VALUES (1, 'ARTICLE', 'Processo di approvazione degli articoli', 'articles', 'id');

INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (1, 1, 'BOZZA', 'INVIA IN APPROVAZIONE', 'BOZZA IN ATTESA DI APPROVAZIONE', null, null, 1, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (2, 1, 'BOZZA IN ATTESA DI APPROVAZIONE', 'PUBBLICA', 'PUBBLICATO', null, 'FSMArticleVisibilityAction', 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (3, 1, 'BOZZA IN ATTESA DI APPROVAZIONE', 'TORNA IN BOZZA', 'BOZZA', null, null, 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (4, 1, 'PUBBLICATO', 'ARCHIVIA', 'ARCHIVIATO', 'FSMArticleArchiviaGuard', 'FSMArticleVisibilityAction', 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (5, 1, 'ARCHIVIATO', 'TORNA IN REVISIONE', 'REVISIONE', 'FSMArticleModificaGuard', null, 0, 1);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (6, 1, 'REVISIONE', 'ARCHIVIA', 'ARCHIVIATO', 'FSMArticleArchiviaGuard', null, 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (8, 1, 'PUBBLICATO', 'NASCONDI', 'REVISIONE', 'FSMArticleNascondiGuard', 'FSMArticleVisibilityAction', 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (9, 1, 'REVISIONE IN ATTESA DI APPROVAZIONE', 'PUBBLICA', 'PUBBLICATO', 'FSMArticlePubblicaUnaRevisioneGuard', 'FSMArticleVisibilityAction', 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (10, 1, 'PUBBLICATO', 'MODIFICA', 'REVISIONE', 'FSMArticleModificaGuard', 'FSMArticleModificaAction', 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (11, 1, 'REVISIONE', 'NASCONDI', 'REVISIONE', 'FSMArticleNascondiGuard', null, 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (12, 1, 'REVISIONE IN ATTESA DI APPROVAZIONE', 'TORNA IN REVISIONE', 'REVISIONE', null, null, 0, 0);
INSERT INTO cms2015.fsm_transitions (id, id_fsm, state, input_signal, next_state, guard_class_name, action_class_name, initial, final) VALUES (13, 1, 'REVISIONE', 'INVIA IN APPROVAZIONE', 'REVISIONE IN ATTESA DI APPROVAZIONE', null, null, 0, 0);
