-- ALTER TABLE cms2015.blocks ADD id_redazione BIGINT NULL;

INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (1, 'video home page', 'Video', '', 1, 2, '', '', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (3, 'i tre box servizi', 'Servizio', '', 1, 2, 'box_servizio', '', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (5, 'Sopra header', 'ADV1', '', 1, 2, '', '', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (7, 'Sotto Header - prima di slider', 'ADV2', '', 1, 2, '', '', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (9, 'Sotto Slider', 'ADV3', '', 1, 2, '', '', 0, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (11, 'Sotto Tab4 - sopra footer', 'ADV4', '', 1, 2, 'banner', 'BannerBlock:31560|https://www.poliziadistato.it/statics/36/banner_calendario.jpg|https://www.poliziadistato.it/statics/12/banner_calendario_mobile.jpg', 0, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (13, 'Blocco Slider', 'Blocco Slider', '<div></div>', 1, 2, 'box_slider_home', '', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, id_redazione) VALUES (15, 'Elenco servizi accanto Slider', 'Blocco Servizi Home', '<div></div>', 1, 2, 'box', '', 1, 20);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, id_redazione) VALUES (17, '4 Immagini orizzontali sopra footer', 'Tab4 Home', '<div></div>', 1, 2, '', '', 1, 21);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (19, '', 'Servizio ps', null, 1, 2, 'box_servizio', '<div></div>', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (21, 'Blocco Social Home', 'social_home', '<div></div>', 1, 2, '', '', 0, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (23, 'testlk', 'testBlk', '<div></div>', 1, 2, '', '', 1, null);
INSERT INTO cms2015.blocks (id, description, title, html_code, id_site, id_type_block, default_block_helper_name, dynamic_block_class_name, is_visible, COD_EXT) VALUES (25, 'Blocco popup presente in tutte le pagine', 'Popup', '<div></div>', 1, 2, '', '', 1, null);