INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (1, 'Questura Agrigento', 'Questura Agrigento', '2');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (3, 'Questura Alessandria', 'Questura Alessandria', '11');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (5, 'Questura Ancona', 'Questura Ancona', '15');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (7, 'Questura Aosta', 'Questura Aosta', '23');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (9, 'Questura Ascoli Piceno', 'Questura Ascoli Piceno', '26');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (11, 'Questura L''Aquila', 'Questura L''Aquila', '31');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (13, 'Questura Arezzo', 'Questura Arezzo', '37');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (15, 'Questura Asti', 'Questura Asti', '42');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (17, 'Questura Avellino', 'Questura Avellino', '45');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (19, 'Questura Bari', 'Questura Bari', '52');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (21, 'Questura Bergamo', 'Questura Bergamo', '66');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (23, 'Questura Belluno', 'Questura Belluno', '69');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (25, 'Questura Benevento', 'Questura Benevento', '73');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (27, 'Questura Bologna', 'Questura Bologna', '77');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (29, 'Questura Brindisi', 'Questura Brindisi', '85');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (31, 'Questura Brescia', 'Questura Brescia', '91');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (33, 'Questura Bolzano', 'Questura Bolzano', '96');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (35, 'Questura Cagliari', 'Questura Cagliari', '101');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (37, 'Questura Campobasso', 'Questura Campobasso', '109');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (39, 'Questura Caserta', 'Questura Caserta', '113');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (41, 'Questura Chieti', 'Questura Chieti', '123');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (43, 'Questura Caltanissetta', 'Questura Caltanissetta', '128');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (45, 'Questura Cuneo', 'Questura Cuneo', '134');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (47, 'Questura Como', 'Questura Como', '137');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (49, 'Questura Cremona', 'Questura Cremona', '140');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (51, 'Questura Cosenza', 'Questura Cosenza', '144');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (53, 'Questura Catania', 'Questura Catania', '150');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (55, 'Questura Catanzaro', 'Questura Catanzaro', '162');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (57, 'Questura Enna', 'Questura Enna', '166');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (59, 'Questura Ferrara', 'Questura Ferrara', '172');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (61, 'Questura Foggia', 'Questura Foggia', '174');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (63, 'Questura Firenze', 'Questura Firenze', '181');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (65, 'Questura Forlì Cesena', 'Questura Forlì Cesena', '188');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (67, 'Questura Frosinone', 'Questura Frosinone', '192');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (69, 'Questura Genova', 'Questura Genova', '198');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (71, 'Questura Gorizia', 'Questura Gorizia', '211');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (73, 'Questura Grosseto', 'Questura Grosseto', '215');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (75, 'Questura Imperia', 'Questura Imperia', '219');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (77, 'Questura Isernia', 'Questura Isernia', '225');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (79, 'Questura Lecce', 'Questura Lecce', '228');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (81, 'Questura Livorno', 'Questura Livorno', '237');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (83, 'Questura Latina', 'Questura Latina', '246');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (85, 'Questura Lucca', 'Questura Lucca', '255');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (87, 'Questura Macerata', 'Questura Macerata', '259');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (89, 'Questura Messina', 'Questura Messina', '262');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (91, 'Questura Milano', 'Questura Milano', '275');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (93, 'Questura Mantova', 'Questura Mantova', '296');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (95, 'Questura Modena', 'Questura Modena', '299');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (97, 'Questura Massa Carrara', 'Questura Massa Carrara', '305');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (99, 'Questura Matera', 'Questura Matera', '309');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (101, 'Questura Napoli', 'Questura Napoli', '313');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (103, 'Questura Novara', 'Questura Novara', '353');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (105, 'Questura Nuoro', 'Questura Nuoro', '356');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (107, 'Questura Oristano', 'Questura Oristano', '366');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (109, 'Questura Palermo', 'Questura Palermo', '370');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (111, 'Questura Piacenza', 'Questura Piacenza', '390');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (113, 'Questura Padova', 'Questura Padova', '393');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (115, 'Questura Pescara', 'Questura Pescara', '395');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (117, 'Questura Perugia', 'Questura Perugia', '399');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (119, 'Questura Pisa', 'Questura Pisa', '406');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (121, 'Questura Pordenone', 'Questura Pordenone', '411');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (123, 'Questura Parma', 'Questura Parma', '414');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (125, 'Questura Pesaro Urbino', 'Questura Pesaro Urbino', '416');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (127, 'Questura Pistoia', 'Questura Pistoia', '421');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (129, 'Questura Pavia', 'Questura Pavia', '426');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (131, 'Questura Potenza', 'Questura Potenza', '431');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (133, 'Questura Ravenna', 'Questura Ravenna', '435');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (135, 'Questura Reggio Calabria', 'Questura Reggio Calabria', '441');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (137, 'Questura Reggio Emilia', 'Questura Reggio Emilia', '454');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (139, 'Questura Ragusa', 'Questura Ragusa', '457');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (141, 'Questura Rieti', 'Questura Rieti', '463');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (143, 'Questura Roma', 'Questura Roma', '468');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (145, 'Questura Rovigo', 'Questura Rovigo', '524');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (147, 'Questura Salerno', 'Questura Salerno', '530');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (149, 'Questura Siena', 'Questura Siena', '539');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (151, 'Questura Sondrio', 'Questura Sondrio', '544');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (153, 'Questura La Spezia', 'Questura La Spezia', '547');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (155, 'Questura Siracusa', 'Questura Siracusa', '552');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (157, 'Questura Sassari', 'Questura Sassari', '564');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (159, 'Questura Savona', 'Questura Savona', '579');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (161, 'Questura Taranto', 'Questura Taranto', '585');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (163, 'Questura Teramo', 'Questura Teramo', '592');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (165, 'Questura Trento', 'Questura Trento', '596');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (167, 'Questura Torino', 'Questura Torino', '602');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (169, 'Questura Trapani', 'Questura Trapani', '618');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (171, 'Questura Terni', 'Questura Terni', '627');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (173, 'Questura Trieste', 'Questura Trieste', '631');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (175, 'Questura Treviso', 'Questura Treviso', '643');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (177, 'Questura Udine', 'Questura Udine', '647');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (179, 'Questura Varese', 'Questura Varese', '652');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (181, 'Questura Vercelli', 'Questura Vercelli', '656');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (183, 'Questura Venezia', 'Questura Venezia', '659');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (185, 'Questura Vicenza', 'Questura Vicenza', '669');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (187, 'Questura Verona', 'Questura Verona', '673');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (189, 'Questura Viterbo', 'Questura Viterbo', '677');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (191, 'Questura Biella', 'Questura Biella', '681');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (193, 'Questura Crotone', 'Questura Crotone', '683');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (195, 'Questura Lecco', 'Questura Lecco', '687');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (197, 'Questura Lodi', 'Questura Lodi', '689');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (199, 'Questura Prato', 'Questura Prato', '692');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (201, 'Questura Rimini', 'Questura Rimini', '695');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (203, 'Questura Verbano Cusio Ossola', 'Questura Verbano Cusio Ossola', '699');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (205, 'Questura Vibo Valentia', 'Questura Vibo Valentia', '704');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (206, 'Questura Fermo', 'Questura Fermo', '705');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (216, 'Questura Monza e della Brianza', 'Questura Monza e della Brianza', '706');
INSERT INTO fe_questure.cms_questure (id, descrizione, cms_code, cod_ext) VALUES (224, 'Questura Barletta Andria Trani', 'Questura Barletta Andria Trani', null);
