insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (1, 'Palermo', 'dv.1');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (2, 'Roma', 'dv.2');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (3, 'Alessandria', 'dv.3');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (4, 'Cosenza', 'dv.4');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (5, 'Vibo Valentia', 'dv.5');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (6, 'Abbasanta', 'dv.6');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (7, 'Bolzano', 'dv.7');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (8, 'Brescia', 'dv.8');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (9, 'Campobasso', 'dv.9');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (10, 'Caserta', 'dv.10');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (11, 'Cesena', 'dv.11');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (12, 'Foggia', 'dv.12');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (13, 'La Spezia', 'dv.13');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (14, 'Milano', 'dv.14');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (15, 'Moena', 'dv.15');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (16, 'Nettuno', 'dv.16');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (17, 'Pescara', 'dv.17');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (18, 'Peschiera', 'dv.18');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (19, 'Piacenza', 'dv.19');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (20, 'Pratica di Mare', 'dv.20');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (21, 'Senigallia', 'dv.21');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (22, 'Spoleto', 'dv.22');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (23, 'Trieste', 'dv.23');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (24, 'Vicenza', 'dv.24');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (25, 'Bari', 'dv.25');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (26, 'Genova', 'dv.26');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (27, 'Padova', 'dv.27');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (28, 'Ventimiglia', 'dv.28');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (29, 'Duino', 'dv.29');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (30, 'Reggio Emilia', 'dv.30');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (31, 'Taranto', 'dv.31');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (32, 'Bologna', 'dv.32');
insert into fe_doppiavela.corsi_citta (id, descrizione, COD_EXT) values (33, 'Rieti', 'dv.33');