insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (1, 'Agente Ausiliario', 10, 1, 'dv.1');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (2, 'Agente Ausiliario Trattenuto', 20, 1, 'dv.2');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (3, 'Agente Effettivo', 30, 1, 'dv.3');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (4, 'Vice Sovrintendente', 40, 1, 'dv.4');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (5, 'Vice Ispettore', 50, 1, 'dv.5');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (7, 'Vice Commissario', 71, 1, 'dv.7');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (8, 'Vice Questore Aggiunto', 80, 1, 'dv.8');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (9, 'Operatore Tecnico', 31, 1, 'dv.9');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (10, 'Vice Revisore Tecnico', 41, 1, 'dv.10');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (11, 'Vice Perito Tecnico', 51, 1, 'dv.11');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (12, 'Perito Tecnico Superiore', 52, 1, 'dv.12');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (13, 'Primo Dirigente', 90, 1, 'dv.13');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (14, 'Primo Dirigente Medico', 91, 1, 'dv.14');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (15, 'Direttore Tecnico', 81, 1, 'dv.15');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (16, 'C.A.P.S.', 120, 2, 'dv.16');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (17, 'C.A.P.P.COM.', 100, 2, 'dv.17');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (18, 'Allievo Vice Commissario', 70, 1, 'dv.18');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (19, 'C.A.P.Fr.', 110, 2, 'dv.19');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (20, 'Allievo Agente Effettivo', 21, 1, 'dv.20');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (21, 'Allievo Guardia di P.S.', 8, 1, 'dv.21');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (22, 'Guardia di P.S.', 9, 1, 'dv.22');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (23, 'C.A.P.F.', 130, 2, 'dv.23');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (24, 'Motorista Navale Eq. Fisso 1000 Hp', 140, 2, 'dv.24');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (25, 'Vice Brigadiere', 34, 1, 'dv.25');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (26, 'O.C.T.', 135, 2, 'dv.26');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (27, 'Addetto alla Gestione Armamenti', 140, 2, 'dv.27');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (28, 'Operatore scorte e sicurezza', 150, 2, 'dv.28');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (29, 'Videofotosegnalatori', 160, 2, 'dv.29');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (30, 'Interspecialità', 170, 2, 'dv.30');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (31, 'Comandanti di Unità Navale Costiera', 180, 2, 'dv.31');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (32, 'Tutor Mipg-Web', 190, 2, 'dv.32');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (33, 'Istruttore di tiro', 200, 2, 'dv.33');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (34, 'Istruttore di guida operativa', 210, 2, 'dv.34');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (35, 'Istruttore di difesa personale', 220, 2, 'dv.35');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (36, 'Istruttore di tecniche operative', 230, 2, 'dv.36');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (37, 'Dattiloscopisti', 165, 2, 'dv.37');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (38, 'Armaioli', 240, 2, 'dv.38');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (39, 'Squadriglia Antisequestro Eliportati', 250, 2, 'dv.39');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (40, 'Focal Point', 300, 2, 'dv.40');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (41, 'Conduttori cinofili antiesplosivo', 310, 2, 'dv.41');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (42, 'Addestramento NBC-R', 315, 2, 'dv.42');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (43, 'Pilota di aeroplani', 320, 2, 'dv.43');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (44, 'Pilota di elicotteri', 325, 2, 'dv.44');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (45, 'Specialista di aereo o di elicottero', 330, 2, 'dv.45');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (46, 'Carburantista di linea e di deposito', 335, 2, 'dv.46');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (47, 'Dispositivo di sicurezza aereoportuale', 450, 2, 'dv.47');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (48, 'Commissario', 72, 1, 'dv.48');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (49, 'Operatore di motovolante', 152, 2, 'dv.49');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (50, 'POL.G.A.I.', 153, 2, 'dv.50');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (51, 'Polizia dei giochi e delle scommesse', 154, 2, 'dv.51');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (52, 'A.S.P.P.', 155, 2, 'dv.52');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (53, 'R.S.P.P.', 156, 2, 'dv.53');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (54, 'Cavaliere', 157, 2, 'dv.54');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (55, 'Sicurezza e soccorso in montagna', 158, 2, 'dv.55');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (56, 'Esperto in manovre di corda', 460, 2, 'dv.56');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (57, 'Alpinista', 470, 2, 'dv.57');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (58, 'Sci Alpinista', 480, 2, 'dv.58');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (59, 'Corso di specializzazione nei servizi di Polizia Stradale riservato al ruolo degli Ispettori', 490, 2, 'dv.59');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (60, 'Conduttore cinofilo prevenzione generale e soccorso pubblico', 500, 2, 'dv.60');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (61, 'Tiratore scelto', 510, 2, 'dv.61');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (62, 'Direttore di tiro', 520, 2, 'dv.62');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (63, 'I.N.A.D.', 138, 2, 'dv.63');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (64, 'Corso di formazione per formatori di PS Personale', 530, 2, 'dv.64');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (65, 'corso A.P.S. (approccio al primo soccorso)', 540, 2, 'dv.65');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (66, 'Reati contro i minori', 550, 2, 'dv.66');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (67, 'Esperto in falso documentale', 560, 2, 'dv.67');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (68, 'Reparto mobile', 570, 2, 'dv.68');
insert into fe_doppiavela.corsi_tipo (id, descrizione, ordine, id_tipologia, COD_EXT) values (69, 'Tecniche Investigative e Scientifiche', 580, 2, null);